### ISSUE TITLE
weapp全局注册Iconfont无效

### ISSUE THREAD

**Issue by WhileSun** [dongj0316/taro3-vue3-iconfont#1]
- 全局注册
![image](https://user-images.githubusercontent.com/31122836/164971706-f0444094-b719-46c6-a3ef-41317b669cf5.png)
- 配置
![image](https://user-images.githubusercontent.com/31122836/164971720-fad19f4a-e7aa-4c76-b0ea-dd8afb69171b.png)
- 错误信息，图标不展示
![image](https://user-images.githubusercontent.com/31122836/164971769-e290ef70-b7a7-4508-9343-1dbab00fdffb.png)
- 使用
![image](https://user-images.githubusercontent.com/31122836/164971883-93be0abd-4432-4086-9499-5f1b3ee4083e.png)

-直接在page中引入iconfont，显示正常
![image](https://user-images.githubusercontent.com/31122836/164971894-49df67f2-4899-4797-bbc3-59913b106cc1.png)

麻烦大佬看看什么原因~~~

**Comment by dongj0316** [comment]
@WhileSun 组件名称改成Iconfont吧，用icon不行
